paths:
  snapshot_dir: "data/snapshots"
  static_mount: "/static"

security:
  ingest_token: "SHARED_TOKEN_ABC"

yolo:
  device: "cuda"         # hoặc "cpu"
  model: "yolov8n.pt"
  imgsz: 640
  conf: 0.45

alarm:
  enabled: true
  map:
    front_gate: "http://esp32-front.local/alarm/on"
  seconds: 3
  cooldown_s: 10
